# Github Release Notes Configuration
# ref: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
---
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Fixes 🛠
      labels:
        - fix
        - regression
    - title: Features 🎉
      labels:
        - feature
    - title: Other Changes
      labels:
        - "*"