name: "Build Single Ignition Docker Image"

on:
  workflow_dispatch:
    inputs:
      ignition-version:
        description: 'Ignition Version'
        required: true
        default: '8.1.42'
      push:
        description: 'Push to Container Registry'
        required: true
        type: boolean
        default: true  
  release:
    types: [published]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildx Setup
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Determine version and push setting
        id: config
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.ignition-version }}" >> $GITHUB_OUTPUT
            echo "push=${{ inputs.push }}" >> $GITHUB_OUTPUT
          fi

      - name: Build
        uses: docker/bake-action@v5.7.0
        with:
          files: |
            ./docker-bake.hcl
          set: |
            *.args.IGNITION_VERSION=${{ steps.config.outputs.version }}
            *.tags=bwdesigngroup/ignition-docker:${{ steps.config.outputs.version }}
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: ${{ steps.config.outputs.push }}