on:
  workflow_dispatch:
    inputs:
      ignition-version:
        description: 'Ignition Version'
        required: true
        default: '8.1.43'
      push:
        description: 'Push to Docker Hub'
        required: true
        type: boolean
        default: true  

name: "Build Single Ignition Docker Image"

jobs:
  build:
    name: Setup

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildx Setup
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build
        uses: docker/bake-action@v5.7.0
        with:
          files: |
            ./docker-bake.hcl
          set: |
            *.args.IGNITION_VERSION=${{ inputs.ignition-version }}
          push: ${{ inputs.push }}