name: "Build Single Ignition Docker Image"

on:
  workflow_dispatch:
    inputs:
      ignition-version:
        description: 'Ignition Version'
        required: true
        default: '8.1.43'
      push:
        description: 'Push to Container Registry'
        required: true
        type: boolean
        default: true  

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildx Setup
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/bake-action@v5.7.0
        with:
          files: |
            ./docker-bake.hcl
          set: |
            *.args.IGNITION_VERSION=${{ inputs.ignition-version }}
            *.tags=ghcr.io/${{ github.repository }}:${{ inputs.ignition-version }}
          push: ${{ inputs.push }}