name: Build Multiple Ignition Docker Images

on:
  workflow_dispatch:
    inputs:
      base-version:
        description: 'Base version for range build (e.g., 8.1)'
        required: true
        default: '8.1'      
      start-version:
        description: 'Start version for range build (e.g., 22 for 8.1.22)'
        required: true
        default: 22
        type: number
      end-version:
        description: 'End version for range build (e.g., 42 for 8.1.42)'
        required: true
        default: 42
        type: number
      push:
        description: 'Push to Container Registry'
        required: true
        type: boolean
        default: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - id: set-versions
        run: |
          versions=$(seq ${{ inputs.start-version }} ${{ inputs.end-version }} | jq -R -s -c 'split("\n")[:-1]')
          echo "versions=$versions" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare.outputs.versions) }}

    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Buildx Setup
      uses: docker/setup-buildx-action@v3.6.1
    
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/bake-action@v5.7.0
      with:
        files: |
          ./docker-bake.hcl
        set: |
          *.args.IGNITION_VERSION=${{ inputs.base-version }}.${{ matrix.version }}
          *.tags=ghcr.io/${{ github.repository }}:${{ inputs.base-version }}.${{ matrix.version }}
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
        push: ${{ inputs.push }}