on:
  workflow_dispatch:
    inputs:
      start-version:
        description: 'Start version for range build (e.g., 22 for 8.1.22)'
        required: true
        default: '22'
      end-version:
        description: 'End version for range build (e.g., 42 for 8.1.42)'
        required: true
        default: '42'
      push:
        description: 'Push to Docker Hub'
        required: true
        type: boolean
        default: false

name: "Build Multiple Ignition Docker Images"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push
      run: |
        chmod +x ./scripts/build-ignition-versions.sh
        ./scripts/build-ignition-versions.sh ${{ inputs.start-version }} ${{ inputs.end-version }} ${{ inputs.push }}
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled